version: "3"

services:
  my_mongodb:
      image: mongo:latest
      ports:
      - "27017:27017"
      volumes:
      - mongo_db_data:/data/db
      networks:
      - app-network


  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_DB_HOSTNAME=my_mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB=studentsDB_docker
    networks:
      - app-network

volumes:
  mongo_db_data:

networks:
  app-network:
    driver: bridge